rng(42);
x = randn(1, 10);


%% Hold the shape
assert(isequal( ...
    size(x), ...
    size(interfere(x, 2.3)) ...
));


%% Default initial phase is 0.5
assert(isequal( ...
    interfere(x, 3, 'InitialPhase', 0), ...
    interfere(x, 3) ...
));


%% Invert initial phase
assert(all( ...
    interfere(x, 3, 'InitialPhase', pi) + interfere(x, 3) < 1e-6 ...
));
